[HelloPerson]
hash = "sha1-5b49bfdad81fedaeefb224b0ffc2acc58b09cff5"
other = "مرحبا *{{.Name}}* \n معك المساعد الرقمي لمدير المشتريات في شركة قطوف و حلا"

[WhoIsThis]
other = "من معي لطفا؟"

[OnlyText]
other = "أعتذر منك، لا أستطيع التعامل مع المرفقات، سواء رسائل صوتية أو مستندات أو صور أو فديوهات، يرجى إرسال رسائل نصية فقط"